## Preprocessing

In [15]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [16]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_cleaned = application_df.drop(['EIN','NAME'], axis = 1)
application_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(3), object(7)
memory usage: 2.6+ MB

In [17]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
print(application_cleaned.nunique())

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [18]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
app_type_count=application_cleaned['APPLICATION_TYPE'].value_counts()
#pd.DataFrame(app_type_count).columns =['APPLICATION_TYPE', 'count']

print(app_type_count)

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [19]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = ['T9', 'T13', 'T12', 'T2', 'T14', 'T25', 'T15', 'T29', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_cleaned['APPLICATION_TYPE'] = application_cleaned['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_cleaned['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [20]:
# Look at CLASSIFICATION value counts for binning
# YOUR CODE GOES HERE
app_binning = application_cleaned['CLASSIFICATION'].value_counts()
print(app_binning)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [21]:
classification_count = pd.DataFrame(application_cleaned['CLASSIFICATION'].value_counts())
classification_count = classification_count.reset_index(drop=False)
classification_count.columns=['CLASSIFICATION','count']
classification_count
classification_count[classification_count['count']>1]

   CLASSIFICATION  count
0           C1000  17326
1           C2000   6074
2           C1200   4837
3           C3000   1918
4           C2100   1883
5           C7000    777
6           C1700    287
7           C4000    194
8           C5000    116
9           C1270    114
10          C2700    104
11          C2800     95
12          C7100     75
13          C1300     58
14          C1280     50
15          C1230     36
16          C1400     34
17          C7200     32
18          C2300     32
19          C1240     30
20          C8000     20
21          C7120     18
22          C1500     16
23          C1800     15
24          C6000     15
25          C1250     14
26          C8200     11
27          C1238     10
28          C1278     10
29          C1235      9
30          C1237      9
31          C7210      7
32          C2400      6
33          C1720      6
34          C4100      6
35          C1257      5
36          C1600      5
37          C1260      3
38          C2710      3
39             C0      3
40          C3200      2
41          C1234      2
42          C1246      2
43          C1267      2
44          C1256      2

In [22]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = classification_count[classification_count['count']<1883]['CLASSIFICATION']
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_cleaned['CLASSIFICATION'] = application_cleaned['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_cleaned['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [23]:
# Optimize the model by dropping data columns
application_cleaned = application_cleaned[application_cleaned['STATUS']==1]
application_cleaned = application_cleaned.drop(['STATUS'], axis = 1)

application_cleaned = application_cleaned[application_cleaned['SPECIAL_CONSIDERATIONS']=="N"]
application_cleaned = application_cleaned.drop(['SPECIAL_CONSIDERATIONS'], axis = 1)

application_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34268 entries, 0 to 34298
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   APPLICATION_TYPE  34268 non-null  object
 1   AFFILIATION       34268 non-null  object
 2   CLASSIFICATION    34268 non-null  object
 3   USE_CASE          34268 non-null  object
 4   ORGANIZATION      34268 non-null  object
 5   INCOME_AMT        34268 non-null  object
 6   ASK_AMT           34268 non-null  int64
 7   IS_SUCCESSFUL     34268 non-null  int64
dtypes: int64(2), object(6)
memory usage: 2.4+ MB

In [24]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_dummies = pd.get_dummies(application_cleaned)
application_dummies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34268 entries, 0 to 34298
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ASK_AMT                       34268 non-null  int64
 1   IS_SUCCESSFUL                 34268 non-null  int64
 2   APPLICATION_TYPE_Other        34268 non-null  uint8
 3   APPLICATION_TYPE_T10          34268 non-null  uint8
 4   APPLICATION_TYPE_T19          34268 non-null  uint8
 5   APPLICATION_TYPE_T3           34268 non-null  uint8
 6   APPLICATION_TYPE_T4           34268 non-null  uint8
 7   APPLICATION_TYPE_T5           34268 non-null  uint8
 8   APPLICATION_TYPE_T6           34268 non-null  uint8
 9   APPLICATION_TYPE_T7           34268 non-null  uint8
 10  APPLICATION_TYPE_T8           34268 non-null  uint8
 11  AFFILIATION_CompanySponsored  34268 non-null  uint8
 12  AFFILIATION_Family/Parent     34268 non-null  uint8
 13  AFFILIATION_Independent       34268 non-null  uint8
 14  AFFILIATION_National          34268 non-null  uint8
 15  AFFILIATION_Other             34268 non-null  uint8
 16  AFFILIATION_Regional          34268 non-null  uint8
 17  CLASSIFICATION_C1000          34268 non-null  uint8
 18  CLASSIFICATION_C1200          34268 non-null  uint8
 19  CLASSIFICATION_C2000          34268 non-null  uint8
 20  CLASSIFICATION_C2100          34268 non-null  uint8
 21  CLASSIFICATION_C3000          34268 non-null  uint8
 22  CLASSIFICATION_Other          34268 non-null  uint8
 23  USE_CASE_CommunityServ        34268 non-null  uint8
 24  USE_CASE_Heathcare            34268 non-null  uint8
 25  USE_CASE_Other                34268 non-null  uint8
 26  USE_CASE_Preservation         34268 non-null  uint8
 27  USE_CASE_ProductDev           34268 non-null  uint8
 28  ORGANIZATION_Association      34268 non-null  uint8
 29  ORGANIZATION_Co-operative     34268 non-null  uint8
 30  ORGANIZATION_Corporation      34268 non-null  uint8
 31  ORGANIZATION_Trust            34268 non-null  uint8
 32  INCOME_AMT_0                  34268 non-null  uint8
 33  INCOME_AMT_1-9999             34268 non-null  uint8
 34  INCOME_AMT_10000-24999        34268 non-null  uint8
 35  INCOME_AMT_100000-499999      34268 non-null  uint8
 36  INCOME_AMT_10M-50M            34268 non-null  uint8
 37  INCOME_AMT_1M-5M              34268 non-null  uint8
 38  INCOME_AMT_25000-99999        34268 non-null  uint8
 39  INCOME_AMT_50M+               34268 non-null  uint8
 40  INCOME_AMT_5M-10M             34268 non-null  uint8
dtypes: int64(2), uint8(39)
memory usage: 2.1 MB

In [25]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
target = application_dummies['IS_SUCCESSFUL']
features = application_dummies.drop(['IS_SUCCESSFUL'], axis=1)

In [26]:
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
import sklearn as skl
# Use sklearn to split dataset
from sklearn.model_selection import train_test_split
X = features
y = target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state=78)

In [27]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [32]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn_model = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
# Add our first Dense layer, including the input layer
nn_model.add(tf.keras.layers.Dense(units=80, activation="relu", input_shape=(40,)))

# Second hidden layer
#  YOUR CODE GOES HERE
nn_model.add(tf.keras.layers.Dense(units=30, activation="relu", input_shape=(40,)))

# Output layer
#  YOUR CODE GOES HERE
# Add the output layer that uses a probability activation function
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 80)                3280

 dense_7 (Dense)             (None, 30)                2430

 dense_8 (Dense)             (None, 1)                 31

=================================================================
Total params: 5,741
Trainable params: 5,741
Non-trainable params: 0
_________________________________________________________________

In [33]:
# Compile the model
# YOUR CODE GOES HERE
 # Compile the Sequential model together and customize metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Fit the model to the training data
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
718/718 [==============================] - 4s 4ms/step - loss: 0.5698 - accuracy: 0.7189
Epoch 2/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5537 - accuracy: 0.7293
Epoch 3/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5508 - accuracy: 0.7301
Epoch 4/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7323
Epoch 5/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5475 - accuracy: 0.7329
Epoch 6/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5462 - accuracy: 0.7346
Epoch 7/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5452 - accuracy: 0.7330
Epoch 8/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5449 - accuracy: 0.7337
Epoch 9/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7347
Epoch 10/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7347
Epoch 11/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7348
Epoch 12/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5424 - accuracy: 0.7361
Epoch 13/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5424 - accuracy: 0.7362
Epoch 14/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5419 - accuracy: 0.7351
Epoch 15/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7363
Epoch 16/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5417 - accuracy: 0.7364
Epoch 17/100
718/718 [==============================] - 4s 5ms/step - loss: 0.5407 - accuracy: 0.7366
Epoch 18/100
718/718 [==============================] - 3s 5ms/step - loss: 0.5408 - accuracy: 0.7372
Epoch 19/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7371
Epoch 20/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7375
Epoch 21/100
718/718 [==============================] - 4s 5ms/step - loss: 0.5397 - accuracy: 0.7370
Epoch 22/100
718/718 [==============================] - 3s 3ms/step - loss: 0.5390 - accuracy: 0.7375
Epoch 23/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7379
Epoch 24/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5387 - accuracy: 0.7367
Epoch 25/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7377
Epoch 26/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7386
Epoch 27/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7385
Epoch 28/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5382 - accuracy: 0.7375
Epoch 29/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5379 - accuracy: 0.7391
Epoch 30/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5378 - accuracy: 0.7387
Epoch 31/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5378 - accuracy: 0.7388
Epoch 32/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5375 - accuracy: 0.7384
Epoch 33/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7384
Epoch 34/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5376 - accuracy: 0.7386
Epoch 35/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5373 - accuracy: 0.7392
Epoch 36/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7392
Epoch 37/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5361 - accuracy: 0.7386
Epoch 38/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5369 - accuracy: 0.7385
Epoch 39/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7401
Epoch 40/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5365 - accuracy: 0.7387
Epoch 41/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5358 - accuracy: 0.7393
Epoch 42/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5365 - accuracy: 0.7391
Epoch 43/100
718/718 [==============================] - 4s 5ms/step - loss: 0.5362 - accuracy: 0.7397
Epoch 44/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5364 - accuracy: 0.7380
Epoch 45/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5359 - accuracy: 0.7404
Epoch 46/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5353 - accuracy: 0.7397
Epoch 47/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5356 - accuracy: 0.7401
Epoch 48/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7395
Epoch 49/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7398
Epoch 50/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5351 - accuracy: 0.7405
Epoch 51/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7404
Epoch 52/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7405
Epoch 53/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5355 - accuracy: 0.7396
Epoch 54/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5346 - accuracy: 0.7398
Epoch 55/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5347 - accuracy: 0.7399
Epoch 56/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7409
Epoch 57/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7401
Epoch 58/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5347 - accuracy: 0.7409
Epoch 59/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5348 - accuracy: 0.7400
Epoch 60/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5349 - accuracy: 0.7394
Epoch 61/100
718/718 [==============================] - 3s 5ms/step - loss: 0.5346 - accuracy: 0.7401
Epoch 62/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5340 - accuracy: 0.7391
Epoch 63/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5342 - accuracy: 0.7398
Epoch 64/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5347 - accuracy: 0.7401
Epoch 65/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5341 - accuracy: 0.7413
Epoch 66/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5336 - accuracy: 0.7408
Epoch 67/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5341 - accuracy: 0.7411
Epoch 68/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5340 - accuracy: 0.7405
Epoch 69/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5343 - accuracy: 0.7406
Epoch 70/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5342 - accuracy: 0.7407
Epoch 71/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5340 - accuracy: 0.7396
Epoch 72/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5337 - accuracy: 0.7411
Epoch 73/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5337 - accuracy: 0.7411
Epoch 74/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5338 - accuracy: 0.7396
Epoch 75/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5336 - accuracy: 0.7408
Epoch 76/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5336 - accuracy: 0.7406
Epoch 77/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5333 - accuracy: 0.7399
Epoch 78/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5334 - accuracy: 0.7410
Epoch 79/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5334 - accuracy: 0.7410
Epoch 80/100
718/718 [==============================] - 3s 4ms/step - loss: 0.5333 - accuracy: 0.7413
Epoch 81/100

718/718 [==============================] - 2s 3ms/step - loss: 0.5330 - accuracy: 0.7410
Epoch 82/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7414
Epoch 83/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7402
Epoch 84/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7402
Epoch 85/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7401
Epoch 86/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5325 - accuracy: 0.7414
Epoch 87/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7409
Epoch 88/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7411
Epoch 89/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.7414
Epoch 90/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.7406
Epoch 91/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.7410
Epoch 92/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7407
Epoch 93/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5327 - accuracy: 0.7401
Epoch 94/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.7415
Epoch 95/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5324 - accuracy: 0.7412
Epoch 96/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.7409
Epoch 97/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5322 - accuracy: 0.7411
Epoch 98/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5327 - accuracy: 0.7406
Epoch 99/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5322 - accuracy: 0.7411
Epoch 100/100
718/718 [==============================] - 2s 3ms/step - loss: 0.5324 - accuracy: 0.7408

In [34]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

354/354 - 1s - loss: 0.5642 - accuracy: 0.7272 - 665ms/epoch - 2ms/step
Loss: 0.5641758441925049, Accuracy: 0.7272084355354309

In [84]:
application_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(3), object(7)
memory usage: 2.6+ MB

In [35]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn_model = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
# Add our first Dense layer, including the input layer
nn_model.add(tf.keras.layers.Dense(units=80, activation="relu", input_shape=(40,)))

# Second hidden layer
#  YOUR CODE GOES HERE
nn_model.add(tf.keras.layers.Dense(units=30, activation="relu", input_shape=(40,)))

# Third hidden layer
#  YOUR CODE GOES HERE
nn_model.add(tf.keras.layers.Dense(units=20, activation="relu", input_shape=(40,)))


# Output layer
#  YOUR CODE GOES HERE
# Add the output layer that uses a probability activation function
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 80)                3280

 dense_10 (Dense)            (None, 30)                2430

 dense_11 (Dense)            (None, 20)                620

 dense_12 (Dense)            (None, 1)                 21

=================================================================
Total params: 6,351
Trainable params: 6,351
Non-trainable params: 0
_________________________________________________________________

In [36]:
# Compile the model
# YOUR CODE GOES HERE
 # Compile the Sequential model together and customize metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Fit the model to the training data
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
718/718 [==============================] - 4s 4ms/step - loss: 0.5701 - accuracy: 0.7219
Epoch 2/50
718/718 [==============================] - 2s 3ms/step - loss: 0.5537 - accuracy: 0.7299
Epoch 3/50
718/718 [==============================] - 2s 3ms/step - loss: 0.5496 - accuracy: 0.7313
Epoch 4/50
718/718 [==============================] - 4s 5ms/step - loss: 0.5476 - accuracy: 0.7334
Epoch 5/50
718/718 [==============================] - 3s 4ms/step - loss: 0.5470 - accuracy: 0.7332
Epoch 6/50
718/718 [==============================] - 2s 3ms/step - loss: 0.5468 - accuracy: 0.7342
Epoch 7/50
718/718 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7331
Epoch 8/50
718/718 [==============================] - 3s 5ms/step - loss: 0.5454 - accuracy: 0.7336
Epoch 9/50
718/718 [==============================] - 3s 4ms/step - loss: 0.5442 - accuracy: 0.7347
Epoch 10/50
718/718 [==============================] - 2s 3ms/step - loss: 0.5438 - accuracy: 0.7356
Epoch 11/50
718/718 [==============================] - 4s 5ms/step - loss: 0.5431 - accuracy: 0.7345
Epoch 12/50
718/718 [==============================] - 5s 6ms/step - loss: 0.5430 - accuracy: 0.7340
Epoch 13/50
718/718 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7350
Epoch 14/50
718/718 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7358
Epoch 15/50
718/718 [==============================] - 3s 4ms/step - loss: 0.5413 - accuracy: 0.7356
Epoch 16/50
718/718 [==============================] - 3s 4ms/step - loss: 0.5409 - accuracy: 0.7359
Epoch 17/50
718/718 [==============================] - 3s 4ms/step - loss: 0.5407 - accuracy: 0.7382
Epoch 18/50
718/718 [==============================] - 5s 7ms/step - loss: 0.5402 - accuracy: 0.7371
Epoch 19/50
718/718 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7375
Epoch 20/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7366
Epoch 21/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7377
Epoch 22/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7376
Epoch 23/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7388
Epoch 24/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7372
Epoch 25/50
718/718 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7386
Epoch 26/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7385
Epoch 27/50
718/718 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7384
Epoch 28/50
718/718 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7383
Epoch 29/50
718/718 [==============================] - 4s 5ms/step - loss: 0.5376 - accuracy: 0.7388
Epoch 30/50
718/718 [==============================] - 4s 6ms/step - loss: 0.5374 - accuracy: 0.7383
Epoch 31/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7378
Epoch 32/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7394
Epoch 33/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7393
Epoch 34/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7387
Epoch 35/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7390
Epoch 36/50
718/718 [==============================] - 4s 5ms/step - loss: 0.5359 - accuracy: 0.7388
Epoch 37/50
718/718 [==============================] - 4s 6ms/step - loss: 0.5364 - accuracy: 0.7393
Epoch 38/50
718/718 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7398
Epoch 39/50
718/718 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7394
Epoch 40/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7403
Epoch 41/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7407
Epoch 42/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7404
Epoch 43/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7401
Epoch 44/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7388
Epoch 45/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7391
Epoch 46/50
718/718 [==============================] - 2s 3ms/step - loss: 0.5349 - accuracy: 0.7390
Epoch 47/50
718/718 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7402
Epoch 48/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7405
Epoch 49/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7398
Epoch 50/50
718/718 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7404

In [37]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

354/354 - 1s - loss: 0.5639 - accuracy: 0.7284 - 675ms/epoch - 2ms/step
Loss: 0.5639301538467407, Accuracy: 0.7283579707145691

In [39]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
#nn.to_hdf('neural_network.h5', key='df', mode='w')
s = pd.Series([X_train_scaled, y_train, X_test_scaled,y_test])  
s.to_hdf('AlphabetSoupCharity_Optimization.h5', key='s')